# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae720a9b5b312caca2a3ab1dc0e91768216f6fbdcd3e265a1c790f30b65ef5a12e2de1b0974d2254a0e8f8b872ebbfabc7bb632724089fe11df8486f1170f58d

test:
  secret_key_base: 3c591a020da845f20c857a86c9f26591df4b38a5018791fed68c62aaf7b72849c304f22a90538c9aba3bd4782a0757c353fbf1900b8795a88ddaf05515ee2601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
